import os
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

API_PROVIDERS = {
    "deepseek": {
        "name": "DeepSeek",
        "api_base_url": "https://api.deepseek.com",
        "api_key": "",
        "model": "deepseek-chat",
        "max_tokens": 4096,
        "temperature": 0.7,
        "enabled": False,
        "provider_type": "api",
    },
    "ollama": {
        "name": "Ollama (本地)",
        "api_base_url": "http://localhost:11434",
        "api_key": "ollama",
        "model": "huihui_ai/qwen3.5-abliterated:0.8B",
        "max_tokens": 1024,
        "temperature": 0.7,
        "enabled": True,
        "think": False,
        "provider_type": "local",
    },
    "openai": {
        "name": "OpenAI（通用）",
        "api_base_url": "https://apis.iflow.cn/v1",
        "api_key": "",
        "model": "deepseek-v3.2",
        "max_tokens": 1024,
        "temperature": 0.7,
        "enabled": True,
        "think": False,
        "provider_type": "api",
    },
    "doubao": {
        "name": "豆包",
        "api_base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "api_key": "",
        "model": "doubao-seed-2-0-lite-260215",
        "max_tokens": 1024,
        "temperature": 0.7,
        "enabled": True,
        "think": False,
        "provider_type": "api",
    },
    "anthropic": {
        "name": "Anthropic Claude",
        "api_base_url": "https://api.anthropic.com/v1",
        "api_key": "",
        "model": "claude-sonnet-4-6",
        "max_tokens": 1024,
        "temperature": 0.7,
        "enabled": False,
        "provider_type": "api",
    },
    "azure_openai": {
        "name": "Azure OpenAI",
        "api_base_url": "",
        "api_key": "",
        "model": "gpt-4",
        "max_tokens": 1024,
        "temperature": 0.7,
        "enabled": False,
        "provider_type": "api",
    },
}
